server:
  port: 8080

spring:
  application:
    name: studycafe
  datasource:
    url: ${DB_URL:jdbc:h2:mem:studycafe;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: Asia/Seoul

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.security: INFO
